{
 "openapi":"3.1.0",
 "info":{
  "title":"Infobip OpenAPI Specification",
  "description":"OpenAPI Specification that contains all public endpoints and webhooks.",
  "contact":{
   "name":"Infobip support",
   "email":"support@infobip.com"
  },
  "version":"3.210.0",
  "x-generatedAt":"2026-07-23T15:23:48.980338559Z"
 },
 "tags":[
  {
   "name":"channels",
   "description":"Create a perfect customer experience by using the channels your customer already use and love.\n",
   "x-type":"category",
   "x-displayName":"Channels"
  },
  {
   "name":"live-chat",
   "description":"Infobip Live Chat product offers real-time chat communication with customer on your website or in through your mobile app. More information about the product you can find at [Live Chat product documentation](https://www.infobip.com/docs/live-chat).",
   "x-type":"product",
   "x-displayName":"Live Chat"
  }
 ],
 "paths":{
  "/livechat/1/widgets/{widgetId}/sessions/{sessionId}":{
   "delete":{
    "tags":[
     "channels",
     "live-chat"
    ],
    "summary":"Invalidate customer session",
    "description":"This method enables you to invalidate an [authenticated Live Chat web session](https://www.infobip.com/docs/live-chat/users-and-authentication#web-authentication).\n      Session invalidation is performed whenever you wish to explicitly terminate an authenticated session, for example on user log out or due to security concerns.",
    "operationId":"invalidate-customer-session",
    "parameters":[
     {
      "name":"widgetId",
      "in":"path",
      "description":"Unique identifier of your widget. You can obtain the identifier from the [widget configuration page](https://portal.infobip.com/apps/livechat) or from the widget installation snippet.",
      "required":true,
      "style":"simple",
      "explode":false,
      "schema":{
       "type":"string",
       "format":"uuid"
      }
     },
     {
      "name":"sessionId",
      "in":"path",
      "description":"Unique identifier of user session to be invalidated. For more information on session identifiers, see the **SID** parameter in [personalization token](https://www.infobip.com/docs/live-chat/users-and-authentication#generate-the-personalization-token-web-authentication) documentation.",
      "required":true,
      "style":"simple",
      "explode":false,
      "schema":{
       "type":"string"
      }
     }
    ],
    "responses":{
     "204":{
      "description":"No Content"
     },
     "401":{
      "$ref":"#/components/responses/ApiException401"
     },
     "403":{
      "$ref":"#/components/responses/ApiException403"
     },
     "404":{
      "$ref":"#/components/responses/ApiException404"
     },
     "500":{
      "$ref":"#/components/responses/ApiException500"
     }
    },
    "security":[
     {
      "IBSSOTokenHeader":[]
     },
     {
      "APIKeyHeader":[]
     },
     {
      "Basic":[]
     },
     {
      "OAuth2":[]
     }
    ],
    "x-scopes":[
     "live-chat:manage"
    ]
   }
  }
 },
 "components":{
  "schemas":{
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardAction":{
    "type":"object",
    "description":"List of buttons displayed on the card.",
    "discriminator":{
     "propertyName":"type",
     "mapping":{
      "URL":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.URLCardAction",
      "POSTBACK_DATA":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.PostbackCardAction"
     }
    },
    "properties":{
     "type":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardActionType"
     }
    },
    "title":"CardAction"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardActionType":{
    "type":"string",
    "enum":[
     "URL",
     "POSTBACK_DATA"
    ],
    "title":"CardActionType"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardContent":{
    "type":"object",
    "description":"A list of cards within the carousel.",
    "properties":{
     "title":{
      "type":"string",
      "description":"Card title, displayed as bold text.",
      "example":"Card title",
      "maxLength":200,
      "minLength":1
     },
     "description":{
      "type":"string",
      "description":"Card description, displayed as regular text.",
      "example":"Some super cool, attention-grabbing description",
      "maxLength":2000,
      "minLength":1
     },
     "imageUrl":{
      "type":"string",
      "description":"Card image URL.",
      "example":"https://www.infobip.com/infobip-logo.png"
     },
     "cardActions":{
      "type":"array",
      "description":"List of buttons displayed on the card.",
      "items":{
       "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardAction"
      },
      "maxItems":4,
      "minItems":0
     }
    },
    "required":[
     "description"
    ],
    "title":"CardContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatButtonResponsePayloadType":{
    "type":"string",
    "description":"Button action type.",
    "enum":[
     "URL",
     "POSTBACK"
    ],
    "title":"LiveChatButtonResponsePayloadType"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundAudioContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2000,
        "minLength":0
       },
       "id":{
        "type":"string",
        "description":"Unique media identifier."
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatInboundAudioContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundBundleContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "inboundMessage":{
        "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
       },
       "outboundMessages":{
        "type":"array",
        "description":"Welcome messages displayed to the end user.",
        "items":{
         "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundTimestampedContent"
        }
       }
      }
     }
    ],
    "required":[
     "inboundMessage",
     "outboundMessages"
    ],
    "title":"LiveChatInboundBundleContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundButtonResponseContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "text":{
        "type":"string",
        "description":"Card button title."
       },
       "payloadType":{
        "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatButtonResponsePayloadType"
       },
       "payload":{
        "type":"string",
        "description":"Button payload."
       }
      }
     }
    ],
    "required":[
     "payloadType",
     "text"
    ],
    "title":"LiveChatInboundButtonResponseContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent":{
    "type":"object",
    "description":"Message content.",
    "discriminator":{
     "propertyName":"type",
     "mapping":{
      "TEXT":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundTextContent",
      "IMAGE":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundImageContent",
      "VIDEO":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundVideoContent",
      "AUDIO":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundAudioContent",
      "DOCUMENT":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundDocumentContent",
      "SURVEY_RESPONSE":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundSurveyResponseContent",
      "BUTTON_RESPONSE":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundButtonResponseContent",
      "BUNDLE":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundBundleContent",
      "CUSTOM_DATA":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundCustomDataContent"
     }
    },
    "properties":{
     "type":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContentType"
     }
    },
    "title":"LiveChatInboundContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContentType":{
    "type":"string",
    "enum":[
     "TEXT",
     "IMAGE",
     "VIDEO",
     "AUDIO",
     "DOCUMENT",
     "SURVEY_RESPONSE",
     "PRE_CHAT_FORM",
     "FORM_RESPONSE",
     "BUTTON_RESPONSE",
     "BUNDLE",
     "CUSTOM_DATA"
    ],
    "title":"LiveChatInboundContentType"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundCustomDataContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "agentMessage":{
        "type":"string",
        "description":"The message for the agent. Leave empty if no message should be displayed.",
        "maxLength":4096,
        "minLength":0
       },
       "userMessage":{
        "type":"string",
        "description":"The message for the customer. Leave empty if no message should be displayed.",
        "maxLength":4096,
        "minLength":0
       },
       "customData":{
        "type":"object",
        "additionalProperties":{
         "type":"object"
        },
        "description":"Custom data content."
       }
      }
     }
    ],
    "title":"LiveChatInboundCustomDataContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundDocumentContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2000,
        "minLength":0
       },
       "caption":{
        "type":"string",
        "description":"Media caption.",
        "maxLength":3000,
        "minLength":0
       },
       "id":{
        "type":"string",
        "description":"Unique media identifier."
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatInboundDocumentContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundImageContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2000,
        "minLength":0
       },
       "caption":{
        "type":"string",
        "description":"Media caption.",
        "maxLength":3000,
        "minLength":0
       },
       "id":{
        "type":"string",
        "description":"Unique media identifier."
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatInboundImageContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundSurveyResponseContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "surveySatisfaction":{
        "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.SurveyResponseSatisfaction"
       },
       "message":{
        "type":"string",
        "description":"Feedback text."
       }
      }
     }
    ],
    "required":[
     "surveySatisfaction"
    ],
    "title":"LiveChatInboundSurveyResponseContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundTextContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "text":{
        "type":"string",
        "description":"The content of the message sent by the end user.",
        "maxLength":4096,
        "minLength":1
       }
      }
     }
    ],
    "required":[
     "text"
    ],
    "title":"LiveChatInboundTextContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundUserData":{
    "type":"object",
    "description":"Data about the user who sent the message.",
    "properties":{
     "cdpPersonId":{
      "type":"integer",
      "format":"int64",
      "description":"Internal person ID in People."
     },
     "userIdentity":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundUserIdentity"
     }
    },
    "required":[
     "cdpPersonId"
    ],
    "title":"LiveChatInboundUserData"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundUserIdentity":{
    "type":"object",
    "description":"Information about the user who sent the message.",
    "properties":{
     "identityType":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundUserIdentityType"
     },
     "identityValue":{
      "type":"string",
      "description":"Unique Person identifier."
     },
     "pushRegistrationId":{
      "type":"string",
      "description":"Push registration ID."
     }
    },
    "required":[
     "identityType",
     "identityValue"
    ],
    "title":"LiveChatInboundUserIdentity"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundUserIdentityType":{
    "type":"string",
    "description":"Unique Person identifier type.",
    "enum":[
     "EMAIL",
     "PHONE",
     "EXTERNAL_ID"
    ],
    "title":"LiveChatInboundUserIdentityType"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundVideoContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2000,
        "minLength":0
       },
       "caption":{
        "type":"string",
        "description":"Media caption.",
        "maxLength":3000,
        "minLength":0
       },
       "id":{
        "type":"string",
        "description":"Unique media identifier."
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatInboundVideoContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundAudioContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2000,
        "minLength":0
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatOutboundAudioContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundButtonContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "text":{
        "type":"string",
        "description":"Message text."
       },
       "url":{
        "type":"string",
        "description":"URL.",
        "maxLength":800,
        "minLength":0
       },
       "buttonPayloads":{
        "type":"array",
        "description":"Card buttons.",
        "items":{
         "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundButtonPayload"
        }
       }
      }
     }
    ],
    "required":[
     "text"
    ],
    "title":"LiveChatOutboundButtonContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundButtonPayload":{
    "type":"object",
    "description":"Card buttons.",
    "properties":{
     "title":{
      "type":"string",
      "description":"Button title."
     },
     "type":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundButtonPayloadType"
     },
     "payload":{
      "type":"string",
      "description":"Unique identifier for 'call to action' buttons."
     }
    },
    "required":[
     "payload",
     "title",
     "type"
    ],
    "title":"LiveChatOutboundButtonPayload"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundButtonPayloadType":{
    "type":"string",
    "description":"Button action.",
    "enum":[
     "URL",
     "POSTBACK"
    ],
    "title":"LiveChatOutboundButtonPayloadType"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundCarouselContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "cards":{
        "type":"array",
        "description":"A list of cards within the carousel.",
        "items":{
         "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardContent"
        },
        "maxItems":10,
        "minItems":2
       },
       "quickReplies":{
        "type":"array",
        "description":"A list of suggested actions independent from the cards.",
        "items":{
         "type":"string",
         "description":"A list of suggested actions independent from the cards."
        }
       }
      }
     }
    ],
    "required":[
     "cards"
    ],
    "title":"LiveChatOutboundCarouselContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent":{
    "type":"object",
    "description":"Messages sent to the end user.",
    "discriminator":{
     "propertyName":"type",
     "mapping":{
      "TEXT":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundTextContent",
      "IMAGE":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundImageWithCaptionContent",
      "VIDEO":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundVideoWithCaptionContent",
      "AUDIO":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundAudioContent",
      "LIVE_CHAT_BUTTON":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundButtonContent",
      "DOCUMENT":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundDocumentWithCaptionContent",
      "SURVEY_REQUEST":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundSurveyRequestContent",
      "QUICK_REPLY":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundQuickReplyContent",
      "CAROUSEL":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundCarouselContent",
      "CUSTOM_DATA":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundCustomDataContent"
     }
    },
    "properties":{
     "type":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContentType"
     }
    },
    "title":"LiveChatOutboundContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContentType":{
    "type":"string",
    "enum":[
     "TEXT",
     "IMAGE",
     "VIDEO",
     "AUDIO",
     "LIVE_CHAT_BUTTON",
     "DOCUMENT",
     "SURVEY_REQUEST",
     "QUICK_REPLY",
     "CAROUSEL",
     "LIVE_CHAT_KNOWLEDGE_BASE_ARTICLE",
     "LIVE_CHAT_KNOWLEDGE_BASE_SEARCH",
     "CUSTOM_DATA"
    ],
    "title":"LiveChatOutboundContentType"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundCustomDataContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "agentMessage":{
        "type":"string",
        "description":"The message for the agent. Leave empty if no message should be displayed.",
        "maxLength":4096,
        "minLength":0
       },
       "userMessage":{
        "type":"string",
        "description":"The message for the customer. Leave empty if no message should be displayed.",
        "maxLength":4096,
        "minLength":0
       },
       "customData":{
        "type":"object",
        "additionalProperties":{
         "type":"object"
        },
        "description":"Custom data content."
       }
      }
     }
    ],
    "title":"LiveChatOutboundCustomDataContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundDocumentWithCaptionContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2048,
        "minLength":0
       },
       "caption":{
        "type":"string",
        "description":"Media caption.",
        "maxLength":240,
        "minLength":0
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatOutboundDocumentWithCaptionContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundImageWithCaptionContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2048,
        "minLength":0
       },
       "caption":{
        "type":"string",
        "description":"Media caption.",
        "maxLength":3000,
        "minLength":0
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatOutboundImageWithCaptionContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundQuickReplyContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "suggestedReplies":{
        "type":"array",
        "description":"Predefined message suggestions to easily start a conversation.",
        "items":{
         "type":"string",
         "description":"Predefined message suggestions to easily start a conversation."
        }
       },
       "source":{
        "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
       },
       "reply":{
        "type":"string",
        "description":"End user response."
       }
      }
     }
    ],
    "required":[
     "source",
     "suggestedReplies"
    ],
    "title":"LiveChatOutboundQuickReplyContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundSurveyRequestContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "question":{
        "type":"string",
        "description":"Survey content.",
        "maxLength":1000,
        "minLength":0
       },
       "followUpQuestion":{
        "type":"string",
        "description":"Feedback question."
       },
       "positiveAnswer":{
        "type":"string",
        "description":"Text displayed as a positive response."
       },
       "negativeAnswer":{
        "type":"string",
        "description":"Text displayed as a negative response."
       },
       "followUpQuestionEnabled":{
        "type":"boolean",
        "description":"Indicates whether the feedback question should be displayed."
       }
      }
     }
    ],
    "required":[
     "followUpQuestionEnabled",
     "question"
    ],
    "title":"LiveChatOutboundSurveyRequestContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundTextContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "text":{
        "type":"string",
        "description":"Message content from the end user.",
        "maxLength":4096,
        "minLength":0
       }
      }
     }
    ],
    "required":[
     "text"
    ],
    "title":"LiveChatOutboundTextContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundTimestampedContent":{
    "type":"object",
    "description":"Welcome messages displayed to the end user.",
    "properties":{
     "content":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     "momentMillis":{
      "type":"integer",
      "format":"int64",
      "description":"The time of the first message received from the end user. Millisecond instant, measured from the Java epoch of 1970-01-01T00:00Z (UTC)."
     }
    },
    "required":[
     "content",
     "momentMillis"
    ],
    "title":"LiveChatOutboundTimestampedContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundVideoWithCaptionContent":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatOutboundContent"
     },
     {
      "type":"object",
      "properties":{
       "url":{
        "type":"string",
        "description":"Media download URL.",
        "maxLength":2048,
        "minLength":0
       },
       "caption":{
        "type":"string",
        "description":"Media caption.",
        "maxLength":3000,
        "minLength":0
       }
      }
     }
    ],
    "required":[
     "url"
    ],
    "title":"LiveChatOutboundVideoWithCaptionContent"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LivechatInboundMessage":{
    "type":"object",
    "description":"Incoming messages.",
    "properties":{
     "from":{
      "type":"string",
      "description":"Live Chat registration ID of the person who sent the message."
     },
     "to":{
      "type":"string",
      "description":"Live Chat widget ID which was used to send the message."
     },
     "integrationType":{
      "type":"string",
      "description":"Message channel which was used to send the message. It is always LIVE_CHAT in this case."
     },
     "receivedAt":{
      "type":"string",
      "format":"date-time",
      "description":"Date and time when Infobip received the message."
     },
     "messageId":{
      "type":"string",
      "description":"The ID that uniquely identifies the received message."
     },
     "callbackData":{
      "type":"string",
      "description":"Callback data sent through the ‛callbackData‛ field when sending a message."
     },
     "message":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundContent"
     },
     "threadId":{
      "type":"string",
      "description":"The ID that uniquely identifies the conversation thread."
     },
     "currentLanguage":{
      "type":"string",
      "description":"Widget language at the time the message was sent."
     },
     "userData":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LiveChatInboundUserData"
     },
     "price":{
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.MessagePrice"
     }
    },
    "required":[
     "from",
     "integrationType",
     "message",
     "messageId",
     "price",
     "receivedAt",
     "to"
    ],
    "title":"LivechatInboundMessage"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LivechatInboundMessages":{
    "type":"object",
    "properties":{
     "results":{
      "type":"array",
      "description":"Incoming messages.",
      "items":{
       "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LivechatInboundMessage"
      }
     },
     "messageCount":{
      "type":"integer",
      "format":"int32",
      "description":"The number of messages returned in the results array."
     },
     "pendingMessageCount":{
      "type":"integer",
      "format":"int32",
      "description":"The number of messages that have not been pulled in."
     }
    },
    "required":[
     "messageCount",
     "pendingMessageCount",
     "results"
    ],
    "title":"LivechatInboundMessages"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.MessagePrice":{
    "type":"object",
    "description":"Sent message price.",
    "properties":{
     "pricePerMessage":{
      "type":"number",
      "description":"Price per one message."
     },
     "currency":{
      "type":"string",
      "description":"The currency in which the price is expressed."
     }
    },
    "title":"MessagePrice"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.PostbackCardAction":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardAction"
     },
     {
      "type":"object",
      "properties":{
       "title":{
        "type":"string",
        "description":"Suggestion text",
        "example":"Pick one!"
       },
       "postbackData":{
        "type":"string",
        "description":"URL or postback data for sending.",
        "example":"REPLY"
       }
      }
     }
    ],
    "required":[
     "postbackData",
     "title"
    ],
    "title":"PostbackCardAction"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.SurveyResponseSatisfaction":{
    "type":"string",
    "description":"Satisfaction indicator.",
    "enum":[
     "SATISFIED",
     "UNSATISFIED"
    ],
    "title":"SurveyResponseSatisfaction"
   },
   "245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.URLCardAction":{
    "type":"object",
    "allOf":[
     {
      "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.CardAction"
     },
     {
      "type":"object",
      "properties":{
       "title":{
        "type":"string",
        "description":"Suggestion text",
        "example":"Pick one!"
       },
       "postbackData":{
        "type":"string",
        "description":"URL or postback data for sending.",
        "example":"REPLY"
       }
      }
     }
    ],
    "required":[
     "postbackData",
     "title"
    ],
    "title":"URLCardAction"
   },
   "ApiException":{
    "type":"object",
    "properties":{
     "requestError":{
      "$ref":"#/components/schemas/ApiRequestError"
     }
    },
    "title":"ApiException"
   },
   "ApiRequestError":{
    "type":"object",
    "properties":{
     "serviceException":{
      "$ref":"#/components/schemas/ApiRequestErrorDetails"
     }
    },
    "title":"ApiRequestError"
   },
   "ApiRequestErrorDetails":{
    "type":"object",
    "properties":{
     "messageId":{
      "type":"string",
      "description":"Identifier of the error."
     },
     "text":{
      "type":"string",
      "description":"Detailed error description."
     },
     "validationErrors":{
      "type":"object",
      "additionalProperties":{
       "type":"array",
       "description":"Validation errors.",
       "items":{
        "type":"string",
        "description":"Validation errors."
       }
      },
      "description":"Validation errors."
     }
    },
    "title":"ApiRequestErrorDetails"
   }
  },
  "responses":{
   "ApiException401":{
    "description":"Unauthorized",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"UNAUTHORIZED",
         "text":"Unauthorized"
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>UNAUTHORIZED</messageId>\n      <text>Unauthorized</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   },
   "ApiException403":{
    "description":"Forbidden",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"FORBIDDEN",
         "text":"Forbidden"
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>FORBIDDEN</messageId>\n      <text>Forbidden</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   },
   "ApiException404":{
    "description":"Not Found",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"NOT_FOUND",
         "text":"Not found"
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>NOT_FOUND</messageId>\n      <text>Not found</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   },
   "ApiException500":{
    "description":"Internal Server Error",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"GENERAL_ERROR",
         "text":"Something went wrong. Please contact support."
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>GENERAL_ERROR</messageId>\n      <text>Something went wrong. Please contact support.</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   }
  },
  "parameters":{},
  "examples":{},
  "requestBodies":{},
  "headers":{},
  "securitySchemes":{
   "APIKeyHeader":{
    "type":"apiKey",
    "description":"This is the most secure authorization type and the one with the most flexibility.\n\nAPI keys can be generated by calling the dedicated API method. Furthermore, API keys can have a limited scope and cover only some API methods. Lastly, they can\nbe revoked at any time. This range of possibilities makes API keys well suited for separating the API access rights across multiple applications or use cases.\nFinally, the loss of an API key is easily manageable.\n\nYou can manage your API keys from [GUI](https://portal.infobip.com/settings/accounts/api-keys), or programmatically\nwith [dedicated API](#platform-&-connectivity/settings).\n\nAPI key Authorization header example:\n\n```shell\nAuthorization: App 003026bbc133714df1834b8638bb496e-8f4b3d9a-e931-478d-a994-28a725159ab9\n```\n",
    "name":"Authorization",
    "in":"header"
   },
   "Basic":{
    "type":"http",
    "description":"Basic authorization type can be used in situations when the API key is not available. For example, API methods for generating API keys should be authenticated\nwith the Basic type.\n\nIn this case, the credentials included in the Authorization header should be a Base64 encoded username and password combination. More formally, basic\nauthentication header can be constructed in three steps:\n\n* Username and password are concatenated using the colon `(:)` as a separator `username:password`.\n* The resulting string is encoded using the [RFC2045-MIME](https://www.ietf.org/rfc/rfc2045.txt) variant of Base64.\n* Encoded string is added as credentials after the `\"Basic \"` type.\n\nExample:\n\n```shell\nUsername: \"Aladdin\"\nPassword: \"openSesame\"\n\nConcatenated string: \"Aladdin:openSesame\"\n\nBase64 encoded string: \"QWxhZGRpbjpvcGVuU2VzYW1l\"\n\nAuthorization header: \"Basic QWxhZGRpbjpvcGVuU2VzYW1l\"\n```\n\n> **Implementation detail**: Base64 encoding is a standard and many available programming languages and frameworks provide convenient methods for encoding\n> strings.\n",
    "scheme":"basic"
   },
   "IBSSOTokenHeader":{
    "type":"apiKey",
    "description":"This authorization type is suited for situations when you do not want to store Infobip credentials in your own app. Instead, your users will input their Infobip\ncredentials every time they access your application and the application will use those credentials to create a session. From then on, the session token can be\nused to authenticate subsequent API requests. Note that the session will expire automatically after a predefined period of inactivity, and can also be manually\nterminated by making an appropriate API call.\n\nYou can find more details on the creation and behavior of the session at\nthe [dedicated documentation page](#platform-connectivity/account-management/create-session).\n\nAfter obtaining the session token by calling the above-referenced API method you can include it in the Authorization header like this:\n\n```shell\nAuthorization: IBSSO 2f9b4d31-2d0d-49a8-85f0-9b862bdca394\n```\n",
    "name":"Authorization",
    "in":"header"
   },
   "OAuth2":{
    "type":"oauth2",
    "description":"Similarly to the IBSSO Token authentication you can use OAuth 2.0 bearer token with Infobip serving both as resource and authorization server. You can obtain\nthe access token using the client credentials grant from `auth/1/oauth2/token` endpoint. It will provide you with your access token, and its expiration period.\nYou can use the token to authorize your API calls until it expires. You can find out more about the process in\nthe [official specification](https://tools.ietf.org/html/rfc6749#section-4.4).\n\nYou can include your access token in the Authorization HTTP request header like this:\n\n```http\nAuthorization: Bearer <access_token>\n```",
    "flows":{
     "clientCredentials":{
      "tokenUrl":"https://api.infobip.com/auth/1/oauth2/token",
      "scopes":{}
     }
    }
   }
  },
  "links":{},
  "callbacks":{}
 },
 "webhooks":{
  "receive-inbound-livechat-messages":{
   "post":{
    "tags":[
     "channels",
     "live-chat"
    ],
    "summary":"Receive Livechat inbound messages",
    "description":"Set up the logic for processing incoming messages to enable customized two-way communication. Inbound messages will be forwarded in real-time to the specified endpoint. [Set the inbound configuration](/docs/api/platform/numbers/my-numbers/resource-management/manage-inbound-configuration) for the number by specifying your endpoint, and we will send inbound Live Chat messages to you.<br/>The name of the default format or renderer for the inbound Live Chat messages is `MO_OTT_CONTACT`, and is documented in this section.",
    "externalDocs":{
     "description":"Learn more about the Live Chat channel and use cases.",
     "url":"https://www.infobip.com/docs/live-chat"
    },
    "operationId":"receive-inbound-livechat-messages",
    "requestBody":{
     "content":{
      "application/json":{
       "schema":{
        "$ref":"#/components/schemas/245a74e48cd7ce0a3e2f108689f6fc8d5a08a4d75c5aeb1883fc983443d62958.LivechatInboundMessages"
       },
       "examples":{
        "Received text message example":{
         "summary":"Received text message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "text":"givenText",
             "type":"TEXT"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        },
        "Received audio message example":{
         "summary":"Received audio message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "url":"https://d3131dgcggnrk5.cloudfront.net/infobiplivechat/C075EA09-80A1-43A4-AF46-0DD60F530DD8?Expires=1729697709&Signature=LH2DOVOw77R292MEJ1uq-BA6xuJkmEPc~kzQYk9tRHJLfDGe8xd2o~Cl1MlA45WI8c7K5som4~4coA496UJBeaJABrV~aFxjpOXrl6riMjqa355Xii~wKU70tMOY5L4tDFfaR6tNWuGYy~Nh~2PIZDdQUxngeyonCwL20Z92rpbsKQYt1sly6WJD4W0ISswcFr8acO47E-JzGBF2AwDMJ7sdaruknIZsCPOEfx9ClX98AuL78jZ0OE1iaNbu7xqt~krhZb4IWX9aBjxZXquHHj5PtZ25DO5e0rJljt~3IZYZ7u4LKV~pwuGExTaS4BcT4WBiuwk6AuTOT4Bd0ae4BQ__&Key-Pair-Id=APKAJKBXNLXMS4C35KIQ",
             "id":"C075EA09-80A1-43A4-AF46-0DD60F530DD8",
             "type":"AUDIO"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        },
        "Received video message example":{
         "summary":"Received video message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "url":"https://d3131dgcggnrk5.cloudfront.net/infobiplivechat/C075EA09-80A1-43A4-AF46-0DD60F530DD8?Expires=1729697709&Signature=LH2DOVOw77R292MEJ1uq-BA6xuJkmEPc~kzQYk9tRHJLfDGe8xd2o~Cl1MlA45WI8c7K5som4~4coA496UJBeaJABrV~aFxjpOXrl6riMjqa355Xii~wKU70tMOY5L4tDFfaR6tNWuGYy~Nh~2PIZDdQUxngeyonCwL20Z92rpbsKQYt1sly6WJD4W0ISswcFr8acO47E-JzGBF2AwDMJ7sdaruknIZsCPOEfx9ClX98AuL78jZ0OE1iaNbu7xqt~krhZb4IWX9aBjxZXquHHj5PtZ25DO5e0rJljt~3IZYZ7u4LKV~pwuGExTaS4BcT4WBiuwk6AuTOT4Bd0ae4BQ__&Key-Pair-Id=APKAJKBXNLXMS4C35KIQ",
             "caption":"Video caption",
             "id":"C075EA09-80A1-43A4-AF46-0DD60F530DD8",
             "type":"VIDEO"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        },
        "Received image message example":{
         "summary":"Received image message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "url":"https://d3131dgcggnrk5.cloudfront.net/infobiplivechat/C075EA09-80A1-43A4-AF46-0DD60F530DD8?Expires=1729697709&Signature=LH2DOVOw77R292MEJ1uq-BA6xuJkmEPc~kzQYk9tRHJLfDGe8xd2o~Cl1MlA45WI8c7K5som4~4coA496UJBeaJABrV~aFxjpOXrl6riMjqa355Xii~wKU70tMOY5L4tDFfaR6tNWuGYy~Nh~2PIZDdQUxngeyonCwL20Z92rpbsKQYt1sly6WJD4W0ISswcFr8acO47E-JzGBF2AwDMJ7sdaruknIZsCPOEfx9ClX98AuL78jZ0OE1iaNbu7xqt~krhZb4IWX9aBjxZXquHHj5PtZ25DO5e0rJljt~3IZYZ7u4LKV~pwuGExTaS4BcT4WBiuwk6AuTOT4Bd0ae4BQ__&Key-Pair-Id=APKAJKBXNLXMS4C35KIQ",
             "caption":"Image caption",
             "id":"C075EA09-80A1-43A4-AF46-0DD60F530DD8",
             "type":"IMAGE"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        },
        "Received document message example":{
         "summary":"Received document message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "url":"https://d3131dgcggnrk5.cloudfront.net/infobiplivechat/C075EA09-80A1-43A4-AF46-0DD60F530DD8?Expires=1729697709&Signature=LH2DOVOw77R292MEJ1uq-BA6xuJkmEPc~kzQYk9tRHJLfDGe8xd2o~Cl1MlA45WI8c7K5som4~4coA496UJBeaJABrV~aFxjpOXrl6riMjqa355Xii~wKU70tMOY5L4tDFfaR6tNWuGYy~Nh~2PIZDdQUxngeyonCwL20Z92rpbsKQYt1sly6WJD4W0ISswcFr8acO47E-JzGBF2AwDMJ7sdaruknIZsCPOEfx9ClX98AuL78jZ0OE1iaNbu7xqt~krhZb4IWX9aBjxZXquHHj5PtZ25DO5e0rJljt~3IZYZ7u4LKV~pwuGExTaS4BcT4WBiuwk6AuTOT4Bd0ae4BQ__&Key-Pair-Id=APKAJKBXNLXMS4C35KIQ",
             "caption":"Document caption",
             "id":"C075EA09-80A1-43A4-AF46-0DD60F530DD8",
             "type":"DOCUMENT"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        },
        "Received survey response message example":{
         "summary":"Received survey response message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "surveySatisfaction":"SATISFIED",
             "message":"Thank you for your help!",
             "type":"SURVEY_RESPONSE"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        },
        "Received bundled message example":{
         "summary":"Received bundled message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "inboundMessage":{
              "text":"Start the chat",
              "type":"TEXT"
             },
             "outboundMessages":[
              {
               "content":{
                "suggestedReplies":[
                 "Start the chat"
                ],
                "source":{
                 "text":"Hello, how can we help you?",
                 "type":"TEXT"
                },
                "reply":"Start the chat",
                "type":"QUICK_REPLY"
               },
               "momentMillis":1727105627
              }
             ],
             "type":"BUNDLE"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        },
        "Received Cards Button message example":{
         "summary":"Received Cards Button message example",
         "value":{
          "results":[
           {
            "from":"ad2086a7-a1ce-40d7-bef0-3f5f4cb2e83b",
            "to":"7f45afb8-0920-4ecd-87f8-a1f8b02225dd",
            "integrationType":"LIVE_CHAT",
            "receivedAt":"2024-09-19T11:52:00.000+0000",
            "messageId":"pmlado1c:msg-95d12702-1162-49fd-af74-3d570dbbc20b:fc0ee343-91ea-4b7d-b53c-381fa58e01ac",
            "message":{
             "inboundMessage":{
              "text":"Information about services",
              "payloadType":"POSTBACK",
              "payload":"servicesInfo",
              "type":"BUTTON_RESPONSE"
             },
             "outboundMessages":[
              {
               "content":{
                "text":"Hello, how can we help you?",
                "url":"",
                "buttonPayloads":[
                 {
                  "title":"Information about products",
                  "type":"POSTBACK",
                  "payload":"productsInfo"
                 },
                 {
                  "title":"Information about services",
                  "type":"POSTBACK",
                  "payload":"servicesInfo"
                 }
                ],
                "type":"LIVE_CHAT_BUTTON"
               },
               "momentMillis":1727105627
              }
             ],
             "type":"BUNDLE"
            },
            "threadId":"26756aab-d4eb-4f87-84df-73b61f8c0840",
            "currentLanguage":"en-US",
            "userData":{
             "cdpPersonId":10313,
             "userIdentity":{
              "identityType":"EMAIL",
              "identityValue":"user@example.com",
              "pushRegistrationId":"40ECB0DE-A338-41F4-9F61-E49495738191"
             }
            },
            "price":{
             "pricePerMessage":0,
             "currency":"EUR"
            }
           }
          ],
          "messageCount":1,
          "pendingMessageCount":0
         }
        }
       }
      }
     }
    },
    "responses":{
     "200":{
      "description":"Your server returns this code if it accepts the callback."
     }
    }
   }
  }
 }
}