{
 "openapi":"3.1.0",
 "info":{
  "title":"Infobip OpenAPI Specification",
  "description":"OpenAPI Specification that contains all public endpoints and webhooks.",
  "contact":{
   "name":"Infobip support",
   "email":"support@infobip.com"
  },
  "version":"3.210.0",
  "x-generatedAt":"2026-07-23T15:24:01.629074755Z"
 },
 "tags":[
  {
   "name":"connectivity",
   "description":"Powerful infrastructure and tools that connect you to the world.\n",
   "x-type":"category",
   "x-displayName":"Connectivity"
  },
  {
   "name":"number-activation-state",
   "description":"Number Activation State are reports with end user numbers that had a change in their activation status. Those would be usually numbers that become deactivated, however sometimes they would also have information about temporary suspensions or re-activations.\n\nNumber state information is provided by our suppliers. To access this information, your business and traffic must be analyzed and approved. This process ensures compliance with regulations. Please contact your Account Manager to request access.\n",
   "x-type":"product",
   "x-displayName":"Number Activation State"
  }
 ],
 "paths":{
  "/number-activation-state/1/network-reports":{
   "get":{
    "tags":[
     "connectivity",
     "number-activation-state"
    ],
    "summary":"Get Network Reports metadata",
    "description":"Get a paginated list of Network Reports metadata.",
    "operationId":"get-reports-metadata",
    "parameters":[
     {
      "name":"page",
      "in":"query",
      "description":"Results page to retrieve (0..N).",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"integer",
       "format":"int32",
       "default":0
      }
     },
     {
      "name":"size",
      "in":"query",
      "description":"Number of records per page.",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"integer",
       "format":"int32",
       "default":20
      }
     },
     {
      "name":"dateFrom",
      "in":"query",
      "description":"Date in UTC that exactly defines the dateFrom property of the reports. <br />Format: yyyy-MM-dd <br />When both dateFrom and dateTo are provided then a list of reports between those two dates are returned.",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"string"
      },
      "example":"2024-03-02"
     },
     {
      "name":"dateTo",
      "in":"query",
      "description":"Date in UTC that exactly defines the dateTo property of the reports. <br />Format: yyyy-MM-dd <br />When both dateFrom and dateTo are provided then a list of reports between those two dates are returned.",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"string"
      },
      "example":"2024-03-03"
     },
     {
      "name":"reportId",
      "in":"query",
      "description":"The reportId to find",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"string"
      },
      "example":"1f7a9938-0e3b-4e20-bb69-4968dca75078"
     },
     {
      "name":"networkId",
      "in":"query",
      "description":"The networkId of network that provided the report content.",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"integer",
       "format":"int32"
      },
      "example":1717
     },
     {
      "name":"networkName",
      "in":"query",
      "description":"The name of network that provided the report content.",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"string"
      },
      "example":"Verizon Wireless"
     },
     {
      "name":"generatedDateFrom",
      "in":"query",
      "description":"Filter by report generation date (inclusive lower bound)",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"string"
      },
      "example":"2024-03-01"
     },
     {
      "name":"generatedDateTo",
      "in":"query",
      "description":"Filter by report generation date (inclusive upper bound)",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"string"
      },
      "example":"2024-03-31"
     }
    ],
    "responses":{
     "200":{
      "description":"OK",
      "content":{
       "application/json":{
        "schema":{
         "$ref":"#/components/schemas/8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.PageReportMetadata"
        },
        "examples":{
         "Response for getting a list of Reports metadata results":{
          "summary":"Response for getting a list of Reports metadata results",
          "value":{
           "results":[
            {
             "reportId":"1f7a9938-0e3b-4e20-bb69-4968dca75078",
             "networkName":"Verizon Wireless",
             "networkId":1717,
             "generatedDate":"2024-03-19T00:00:00Z",
             "dateFrom":"2024-03-19T00:00:00Z",
             "dateTo":"2024-03-20T00:00:00Z",
             "expiryDate":"2024-05-18T00:00:00Z"
            },
            {
             "reportId":"534a3153-0b3d-4408-9bc5-121d3e9c6537",
             "networkName":"AT&T Mobility",
             "networkId":1733,
             "generatedDate":"2024-03-19T00:00:00Z",
             "dateFrom":"2024-03-19T00:00:00Z",
             "dateTo":"2024-03-20T00:00:00Z",
             "expiryDate":"2024-05-18T00:00:00Z"
            }
           ],
           "paging":{
            "page":0,
            "size":2,
            "totalPages":30,
            "totalResults":61
           }
          }
         }
        }
       }
      }
     },
     "401":{
      "$ref":"#/components/responses/ApiException401"
     },
     "403":{
      "$ref":"#/components/responses/ApiException403"
     },
     "429":{
      "$ref":"#/components/responses/ApiException429"
     },
     "500":{
      "$ref":"#/components/responses/ApiException500"
     }
    },
    "security":[
     {
      "IBSSOTokenHeader":[]
     },
     {
      "APIKeyHeader":[]
     },
     {
      "Basic":[]
     },
     {
      "OAuth2":[]
     }
    ],
    "x-scopes":[
     "number-activation-state:read"
    ],
    "x-throttling-info":[
     {
      "type":"time",
      "numberOfRequests":1,
      "numberOfTimeUnits":0,
      "timeUnit":"s"
     }
    ]
   }
  },
  "/number-activation-state/1/network-reports/{reportId}/records":{
   "get":{
    "tags":[
     "connectivity",
     "number-activation-state"
    ],
    "summary":"Get Network Report content",
    "description":"Get a paginated list of destination number activation state changes from a given Report.",
    "operationId":"get-single-report",
    "parameters":[
     {
      "name":"page",
      "in":"query",
      "description":"Results page to retrieve (0..N).",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"integer",
       "format":"int32",
       "default":0
      }
     },
     {
      "name":"size",
      "in":"query",
      "description":"Number of records per page.",
      "required":false,
      "style":"form",
      "explode":true,
      "schema":{
       "type":"integer",
       "format":"int32",
       "default":20
      }
     },
     {
      "name":"reportId",
      "in":"path",
      "description":"The reportId to retrieve",
      "required":true,
      "style":"simple",
      "explode":false,
      "schema":{
       "type":"string"
      }
     }
    ],
    "responses":{
     "200":{
      "description":"OK",
      "content":{
       "application/json":{
        "schema":{
         "$ref":"#/components/schemas/8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.PageReports"
        },
        "examples":{
         "Response for getting a Deactivates Report content":{
          "summary":"Response for getting a Deactivates Report content",
          "value":{
           "results":[
            {
             "date":"2024-03-05T00:00:00.000+0000",
             "destination":"15123456789",
             "type":"DEACTIVATION"
            },
            {
             "date":"2024-03-05T11:00:00.000+0000",
             "destination":"15222222222",
             "type":"DEACTIVATION",
             "newDestination":"15777777777"
            }
           ],
           "paging":{
            "page":1,
            "size":2,
            "totalPages":10,
            "totalResults":21
           }
          }
         }
        }
       }
      }
     },
     "401":{
      "$ref":"#/components/responses/ApiException401"
     },
     "403":{
      "$ref":"#/components/responses/ApiException403"
     },
     "404":{
      "description":"Not Found",
      "content":{
       "*/*":{
        "schema":{
         "type":"object"
        }
       }
      }
     },
     "429":{
      "$ref":"#/components/responses/ApiException429"
     },
     "500":{
      "$ref":"#/components/responses/ApiException500"
     }
    },
    "security":[
     {
      "IBSSOTokenHeader":[]
     },
     {
      "APIKeyHeader":[]
     },
     {
      "Basic":[]
     },
     {
      "OAuth2":[]
     }
    ],
    "x-scopes":[
     "number-activation-state:read"
    ],
    "x-throttling-info":[
     {
      "type":"time",
      "numberOfRequests":1,
      "numberOfTimeUnits":0,
      "timeUnit":"s"
     }
    ]
   }
  }
 },
 "components":{
  "schemas":{
   "8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.DeactivationType":{
    "type":"string",
    "description":"Type of the activation information. Potential values are: <br />    DEACTIVATION - number was deactivated. All messaging to this number must stop. <br />  ACTIVATION - number was activated after being deactivated previously. These numbers must opt-in again to a program to begin any messaging activity. <br />  SUSPENSION - number got suspended. Messaging to this number must be suspended. <br />  REACTIVATION - number was reactivated after being previously suspended. Messaging to this number can resume. <br />",
    "enum":[
     "DEACTIVATION",
     "REACTIVATION",
     "SUSPENSION"
    ],
    "example":"DEACTIVATION",
    "title":"DeactivationType"
   },
   "8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.PageInfo":{
    "type":"object",
    "properties":{
     "page":{
      "type":"integer",
      "format":"int32",
      "description":"Requested page number.",
      "minimum":0
     },
     "size":{
      "type":"integer",
      "format":"int32",
      "description":"Requested page size.",
      "minimum":1
     },
     "totalPages":{
      "type":"integer",
      "format":"int32",
      "description":"The total number of pages of the results matching the requested parameters.",
      "minimum":0
     },
     "totalResults":{
      "type":"integer",
      "format":"int64",
      "description":"The total number of the results matching the requested parameters.",
      "minimum":0
     }
    },
    "required":[
     "page",
     "size",
     "totalPages",
     "totalResults"
    ],
    "title":"PageInfo"
   },
   "8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.PageReportMetadata":{
    "type":"object",
    "properties":{
     "results":{
      "type":"array",
      "items":{
       "$ref":"#/components/schemas/8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.ReportMetadata"
      }
     },
     "paging":{
      "$ref":"#/components/schemas/8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.PageInfo"
     }
    },
    "title":"PageReportMetadata"
   },
   "8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.PageReports":{
    "type":"object",
    "properties":{
     "results":{
      "type":"array",
      "items":{
       "$ref":"#/components/schemas/8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.ReportLineItem"
      }
     },
     "paging":{
      "$ref":"#/components/schemas/8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.PageInfo"
     }
    },
    "title":"PageReports"
   },
   "8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.ReportLineItem":{
    "type":"object",
    "properties":{
     "date":{
      "type":"string",
      "description":"Date in UTC when the activation state change has happened. Format yyyy-MM-dd'T'HH:mm:ss.SSSZ",
      "example":"2024-03-05T11:00:00.000+0000"
     },
     "destination":{
      "type":"string",
      "description":"The phone number that changed its activation state",
      "example":"15987654321"
     },
     "type":{
      "$ref":"#/components/schemas/8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.DeactivationType"
     },
     "newDestination":{
      "type":"string",
      "description":"Optional information about a new phone number that replaced the original deactivated phone number. <br />Only optionally included in case of DEACTIVATION type of the entry",
      "example":"15123456789"
     }
    },
    "required":[
     "date",
     "destination",
     "type"
    ],
    "title":"ReportLineItem"
   },
   "8018948352e80bbff88731d9fb43f611b84a58f2b44c304c63a8e4ae9c4bd661.ReportMetadata":{
    "type":"object",
    "properties":{
     "reportId":{
      "type":"string",
      "description":"The unique reportId. Needed for accessing the report content",
      "example":"138a2a58-0cf3-4ed3-a828-c3dc35eb2bb6",
      "maxLength":64
     },
     "networkName":{
      "type":"string",
      "description":"The name of network that provided the report content.",
      "example":"Verizon Wireless"
     },
     "networkId":{
      "type":"integer",
      "format":"int32",
      "description":"The networkId of network that provided the report content.",
      "example":1717
     },
     "generatedDate":{
      "type":"string",
      "description":"Date in UTC then given report was generated. Format: yyyy-MM-dd",
      "example":"2024-03-09"
     },
     "dateFrom":{
      "type":"string",
      "description":"Date in UTC that defines since when the report has data about activation changes on a given network. <br />Format: yyyy-MM-ddNote that multiple reports for the same date range on the same network are possible. <br />",
      "example":"2024-03-07"
     },
     "dateTo":{
      "type":"string",
      "description":"Date in UTC that defines till when the report has data about activation changes on a given network. <br />Format: yyyy-MM-dd <br />Note that multiple reports for the same date range on the same network are possible.",
      "example":"2024-03-08"
     },
     "expiryDate":{
      "type":"string",
      "description":"Date in UTC that defines when the report will be considered expired and consequently deleted. <br />Format: yyyy-MM-dd",
      "example":"2024-06-08"
     }
    },
    "required":[
     "dateFrom",
     "dateTo",
     "expiryDate",
     "generatedDate",
     "networkId",
     "networkName",
     "reportId"
    ],
    "title":"ReportMetadata"
   },
   "ApiException":{
    "type":"object",
    "properties":{
     "requestError":{
      "$ref":"#/components/schemas/ApiRequestError"
     }
    },
    "title":"ApiException"
   },
   "ApiRequestError":{
    "type":"object",
    "properties":{
     "serviceException":{
      "$ref":"#/components/schemas/ApiRequestErrorDetails"
     }
    },
    "title":"ApiRequestError"
   },
   "ApiRequestErrorDetails":{
    "type":"object",
    "properties":{
     "messageId":{
      "type":"string",
      "description":"Identifier of the error."
     },
     "text":{
      "type":"string",
      "description":"Detailed error description."
     },
     "validationErrors":{
      "type":"object",
      "additionalProperties":{
       "type":"array",
       "description":"Validation errors.",
       "items":{
        "type":"string",
        "description":"Validation errors."
       }
      },
      "description":"Validation errors."
     }
    },
    "title":"ApiRequestErrorDetails"
   }
  },
  "responses":{
   "ApiException401":{
    "description":"Unauthorized",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"UNAUTHORIZED",
         "text":"Unauthorized"
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>UNAUTHORIZED</messageId>\n      <text>Unauthorized</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   },
   "ApiException403":{
    "description":"Forbidden",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"FORBIDDEN",
         "text":"Forbidden"
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>FORBIDDEN</messageId>\n      <text>Forbidden</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   },
   "ApiException429":{
    "description":"Too Many Requests",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"TOO_MANY_REQUESTS",
         "text":"Too many requests"
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>TOO_MANY_REQUESTS</messageId>\n      <text>Too many requests</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   },
   "ApiException500":{
    "description":"Internal Server Error",
    "content":{
     "application/json":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":{
       "requestError":{
        "serviceException":{
         "messageId":"GENERAL_ERROR",
         "text":"Something went wrong. Please contact support."
        }
       }
      }
     },
     "application/xml":{
      "schema":{
       "$ref":"#/components/schemas/ApiException"
      },
      "example":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ApiException>\n  <requestError>\n    <serviceException>\n      <messageId>GENERAL_ERROR</messageId>\n      <text>Something went wrong. Please contact support.</text>\n    </serviceException>\n  </requestError>\n</ApiException>\n"
     }
    }
   }
  },
  "parameters":{},
  "examples":{},
  "requestBodies":{},
  "headers":{},
  "securitySchemes":{
   "APIKeyHeader":{
    "type":"apiKey",
    "description":"This is the most secure authorization type and the one with the most flexibility.\n\nAPI keys can be generated by calling the dedicated API method. Furthermore, API keys can have a limited scope and cover only some API methods. Lastly, they can\nbe revoked at any time. This range of possibilities makes API keys well suited for separating the API access rights across multiple applications or use cases.\nFinally, the loss of an API key is easily manageable.\n\nYou can manage your API keys from [GUI](https://portal.infobip.com/settings/accounts/api-keys), or programmatically\nwith [dedicated API](#platform-&-connectivity/settings).\n\nAPI key Authorization header example:\n\n```shell\nAuthorization: App 003026bbc133714df1834b8638bb496e-8f4b3d9a-e931-478d-a994-28a725159ab9\n```\n",
    "name":"Authorization",
    "in":"header"
   },
   "Basic":{
    "type":"http",
    "description":"Basic authorization type can be used in situations when the API key is not available. For example, API methods for generating API keys should be authenticated\nwith the Basic type.\n\nIn this case, the credentials included in the Authorization header should be a Base64 encoded username and password combination. More formally, basic\nauthentication header can be constructed in three steps:\n\n* Username and password are concatenated using the colon `(:)` as a separator `username:password`.\n* The resulting string is encoded using the [RFC2045-MIME](https://www.ietf.org/rfc/rfc2045.txt) variant of Base64.\n* Encoded string is added as credentials after the `\"Basic \"` type.\n\nExample:\n\n```shell\nUsername: \"Aladdin\"\nPassword: \"openSesame\"\n\nConcatenated string: \"Aladdin:openSesame\"\n\nBase64 encoded string: \"QWxhZGRpbjpvcGVuU2VzYW1l\"\n\nAuthorization header: \"Basic QWxhZGRpbjpvcGVuU2VzYW1l\"\n```\n\n> **Implementation detail**: Base64 encoding is a standard and many available programming languages and frameworks provide convenient methods for encoding\n> strings.\n",
    "scheme":"basic"
   },
   "IBSSOTokenHeader":{
    "type":"apiKey",
    "description":"This authorization type is suited for situations when you do not want to store Infobip credentials in your own app. Instead, your users will input their Infobip\ncredentials every time they access your application and the application will use those credentials to create a session. From then on, the session token can be\nused to authenticate subsequent API requests. Note that the session will expire automatically after a predefined period of inactivity, and can also be manually\nterminated by making an appropriate API call.\n\nYou can find more details on the creation and behavior of the session at\nthe [dedicated documentation page](#platform-connectivity/account-management/create-session).\n\nAfter obtaining the session token by calling the above-referenced API method you can include it in the Authorization header like this:\n\n```shell\nAuthorization: IBSSO 2f9b4d31-2d0d-49a8-85f0-9b862bdca394\n```\n",
    "name":"Authorization",
    "in":"header"
   },
   "OAuth2":{
    "type":"oauth2",
    "description":"Similarly to the IBSSO Token authentication you can use OAuth 2.0 bearer token with Infobip serving both as resource and authorization server. You can obtain\nthe access token using the client credentials grant from `auth/1/oauth2/token` endpoint. It will provide you with your access token, and its expiration period.\nYou can use the token to authorize your API calls until it expires. You can find out more about the process in\nthe [official specification](https://tools.ietf.org/html/rfc6749#section-4.4).\n\nYou can include your access token in the Authorization HTTP request header like this:\n\n```http\nAuthorization: Bearer <access_token>\n```",
    "flows":{
     "clientCredentials":{
      "tokenUrl":"https://api.infobip.com/auth/1/oauth2/token",
      "scopes":{}
     }
    }
   }
  },
  "links":{},
  "callbacks":{}
 }
}